### ISSUE TITLE
Audio stream as Webstream ???

### ISSUE THREAD

**Issue by PD1LOI** [BrandMeister/hoseline#17]
Is it possible the audio stream also play on an external player? like link as http: // servername.com:stream/playlist.m3u8. As an example

**Comment by cyanide-burnout** [comment]
Sorry, it is not possible.

**Comment by PD1LOI** [comment]
Oké tanks

Op 18 sep. 2016 13:32 schreef "Artem Prilutskiy" <notifications@github.com>:

**Comment by tehmaze** [comment]
Transcoding all the streams to mp3 in real time will be very costly. So unless enough sponsors donate hardware this option will not be available.
