### ISSUE TITLE
Wrong call by ID

### ISSUE THREAD

**Issue by ptmtv** [BrandMeister/hoseline#18]
I saw on hoseline when i transmit on a talkgroup a wrong call will be displayed.
2041111 shows PD0DYK David but this must be PE1PTM Ron.
Is it possible to change this?
Many thanks.
73, Ron PE1PTM

**Comment by zarya** [comment]
There are issues with hoseline we know about it as long as the call is good in the lastheard

Hoseline will be fixed but there is not time to fix atm
