### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by s55ma** [BrandMeister/hoseline#24]
There is something wrong with your server configuration. I get this error in the developer tools in Chrome:
WebSocket connection to 'ws://geo.hose.brandmeister.network/hose/293/' failed: Error during WebSocket handshake: Unexpected response code: 400

I can't listen to any conversations. I tried it on 4 different browser: Chrome, Firefox, IE, Opera.

**Comment by tehmaze** [comment]
Unable to reproduce, if this problem persists please reopen this issue.
