### ISSUE TITLE
Confirmation email never received.

### ISSUE THREAD

**Issue by Txnorton** [BrandMeister/hoseline#28]
Registered 5 days ago for Brandmeister but to date no confirmation email.  I have checked both my inbox and spam folder daily to no avail.  When I try to log in it replies account not active wait for email.
It also will not allow me to reregister.

William Norton
AG5KZ

**Comment by tehmaze** [comment]
There are issues with reaching certain destinations, such as all AT&T domains. This is not something we can remediate.
