### ISSUE TITLE
Freeze list when mouse hovering over group link

### ISSUE THREAD

**Issue by chris-tanner** [BrandMeister/hoseline#4]
I keep clicking on links just as the list updates - taking me to the new link that just moved down... not usually the same tg as the one I thought I was clicking on.

**Comment by tehmaze** [comment]
You can also select from the drop down menu. But I think it might be a good idea to check if the user is hovering over the table, and as long as there is movement delay the updating for another 5 seconds.

This needs some more thinking, but I definitely agree that fixing this issue will improve usability.

**Comment by tehmaze** [comment]
This is resolved, the call list will not show new updates as long as the user is hovering over the table. Thanks for the suggestion!
