### ISSUE TITLE
Waiting for server

### ISSUE THREAD

**Issue by Ham-Tech** [BrandMeister/hoseline#5]
Hi

For the last two days, trying to enter any talk group, the "talk group button" onely states "waiting for server"

Is it a general problem or only on my side "of the line"?

Greetings from Tommy

**Comment by tehmaze** [comment]
Will need some more investigation, looks like the web server could do with some more fine tuning to perform better proxying lots of websockets.

**Comment by Ham-Tech** [comment]
Super! 
Thanks for letting us listen oneline, great project!

**Comment by tehmaze** [comment]
We moved to a new proxy for dispatching calls and expanded capacity by adding a new node in the USA, hopefully this will resolve most performance issues.
