### ISSUE TITLE
Reduced audio quality

### ISSUE THREAD

**Issue by crossmod** [BrandMeister/hoseline#6]
Audio quality heard is slightly worse than the same through a repeater (Chrome Version 49.0.2623.87 m).  The NorCal audio meter needed a significantly higher bit rate than the vocoder itself between the source and the streaming server.  But the features and functions on this are excellent!  Nice job guys!

Greg
N6LDJ

**Comment by tehmaze** [comment]
We currently transcode to a-Law to make Hose usable on mobile connections. What does the NorCal audio vocoder use for streaming?

**Comment by tehmaze** [comment]
Just now we deployed a new up-sampling algorithm which should result in better audio.

**Comment by crossmod** [comment]
Hi:

See attached configs; we use an Instreamer for audio to a Shoutcast server
(MPEG2/22 shoutcast sever to browsers.



On Tue, Mar 29, 2016 at 2:59 PM, tehmaze <notifications@github.com> wrote:

> Just now we deployed a new up-sampling algorithm which should result in
> better audio.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BrandMeister/hoseline/issues/6#issuecomment-203130050>
>



-- 

Greg

**Comment by crossmod** [comment]
Sent too soon.  What is your bit rate?

Instreamer (to Shoutcast server) running MPEG2/22kHz sample/64 kbps CBR

Shoutcast to browers is likely MP3? 64 kbps CBR.



On Tue, Mar 29, 2016 at 1:24 PM, tehmaze <notifications@github.com> wrote:

> We currently transcode to a-Law to make Hose usable on mobile connections.
> What does the NorCal audio vocoder use for streaming?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BrandMeister/hoseline/issues/6#issuecomment-203085087>
>



-- 

Greg

**Comment by tehmaze** [comment]
Thanks but we cant use mp3 due to licensing fees that it requires so we have to look into open and free alternatives. a-Law can be used free of charge.

**Comment by cyanide-burnout** [comment]
What the reason to use MP3 on the same bit-rate? More CPU cycles without any profit...

**Comment by tehmaze** [comment]
To answer your question, sample rate is 8kHz with PCM16 samples.

**Comment by crossmod** [comment]
After listening to more traffic, the distortion is more noticeable on the
voice peaks.   Don't know if A-law is the problem through.   You might try
to double or triple the sample rate, but if the rate was too low all the
audio would sound poor (and it does not).  16b samples are fine - if you
are limited on the overall bit rate, try reducing the sample size to offset
the increased sample rate.

Greg
N6LDJ





On Sun, Apr 3, 2016 at 11:08 AM, tehmaze <notifications@github.com> wrote:

> To answer your question, sample rate is 8kHz with PCM16 samples.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BrandMeister/hoseline/issues/6#issuecomment-205023527>
>



-- 

Greg

**Comment by cyanide-burnout** [comment]
Greg,

8 KHz is a sample rate of original codec. We do resampling on the browser side to 48 KHz which is supported by browser.

**Comment by crossmod** [comment]
Ok.  That all should be fine.  Maybe its just a peak level issue.

G

**Comment by tehmaze** [comment]
It could be a rounding issue in the aLaw codec which we're using, needs more investigation.

The encoder may be found here:
 * https://github.com/pd0mz/go-g711/blob/master/alaw.go

And the decoder:
 * http://hose.brandmeister.network/static/js/g711.js

**Comment by crossmod** [comment]
OK.  I am not qualified to play with that stuff....hopefully someone else
can add some insight here.

G

On Tue, Apr 5, 2016 at 3:21 PM, tehmaze <notifications@github.com> wrote:

> It could be a rounding issue in the aLaw codec which we're using, needs
> more investigation.
>
> The encoder may be found here:
>
>    - https://github.com/pd0mz/go-g711/blob/master/alaw.go
>
> And the decoder:
>
>    - http://hose.brandmeister.network/static/js/g711.js
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BrandMeister/hoseline/issues/6#issuecomment-206007992>
>



-- 

Greg

**Comment by tehmaze** [comment]
Audio compressor added in 2.x that should take care of most of the peak noise.
